name: Testing

on:
  push:
    tags:
      - 'testing/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Lua compiler
      run: sudo apt-get -y install lua5.2

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        echo "GIT_TAG=${GITHUB_REF##refs/tags/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Make test files
      run: make files

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-lua-scripts-testing-${{ env.GIT_VER }}
        path: ./obj

    - name: Delete tag
      run: git push origin :${GITHUB_REF}
